package: gleework
version: 0.1.0.0
dependencies:
  - base
  - sdl2
  - random
  - lens
executables:
  gleework:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
